### ISSUE TITLE
Session lock

### ISSUE THREAD

**Issue by mclarty** [tamus-cyber/tamus-control-standards#4]
**Is your content request a correction or amendment? Which security control(s) does it relate to?**
AC-11

**Describe the solution you'd like**
Add language for session lock on workstations.

**Describe alternatives you've considered**
Require session lock, set a maximum timeout, provide for exceptions.

**Comment by paulwiggins** [comment]
Thank you for looking to include AC-11 as a requirement in a future revision of the Texas A&M System Cybersecurity Control Standards & Implementation Guide.

**Comment by mclarty** [comment]
Added to v2.1 draft 2
